### ISSUE TITLE
Please develop a function for bulk claiming points into the wallet

### ISSUE THREAD

**Issue by talentbuilder** [monkipon/qna3-main#1]
The code runs smoothly and the effect is good. Thanks for your nice work.

If a feature for bulk claiming and consolidating points could be developed, it would be even more perfect. I hope this suggestion can be considered.

**Comment by lk0pa** [comment]
你可以加作者的tg，他都在线的，回复很快，不过感觉是个俄罗斯人，你发英文过去就行 ，他主页有写tg地址

**Comment by talentbuilder** [comment]
好的，谢谢回复:)

**Comment by Ricardoseri** [comment]
想问下 这个需要指纹浏览器吗？keys.txt里面是填私钥？

**Comment by monkipon** [comment]
Done!
